-- RUN THIS IN SUPABASE SQL EDITOR

-- 1. Create Campaigns Table
create table campaigns (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  target_amount numeric,
  current_amount numeric default 0,
  category text,
  ngo_address text,
  ipfs_hash text,
  status text default 'PENDING_BLOCKCHAIN',
  blockchain_id numeric unique -- Can be null initially
);

-- 2. Create Donations Table
create table donations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  campaign_id bigint references campaigns(id),
  donor_address text not null,
  amount numeric not null,
  transaction_hash text
);

-- 3. Create Expenses Table
create table expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  campaign_id bigint references campaigns(id), -- Optional link
  milestone_id numeric,
  amount numeric,
  description text,
  ipfs_hash text,
  status text default 'PENDING',
  transaction_hash text
);

-- 4. Enable Realtime
alter publication supabase_realtime add table campaigns;
alter publication supabase_realtime add table donations;
alter publication supabase_realtime add table expenses;
